export const USER_LISTS = 'USER_LISTS'
export const USER_LISTS_LOADING = 'USER_LISTS_LOADING'

export const USER_CREATE_LOADING = 'USER_CREATE_LOADING'
export const USER_CREEATE = 'USER_CREEATE'
export const USER_CREEATE_SUCCESS = 'USER_CREEATE_SUCCESS'
export const USER_CREEATE_FAIL = 'USER_CREEATE_FAIL'


export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const USER_UPDATE_LOADING = 'USER_UPDATE_LOADING'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
