export const USER_LISTS = 'USER_LISTS'
export const USER_LISTS_LOADING = 'USER_LISTS_LOADING'

export const USER_CREATE_LOADING = 'USER_CREATE_LOADING'
export const USER_CREEATE = 'USER_CREEATE'
export const USER_CREEATE_SUCCESS = 'USER_CREEATE_SUCCESS'
export const USER_CREEATE_FAIL = 'USER_CREEATE_FAIL'


